libraryDependencies += "com.lihaoyi"                   %% "os-lib"               % "0.11.6"
libraryDependencies += "com.lihaoyi"                   %% "ujson"                % "4.4.0"
libraryDependencies += "com.lihaoyi"                   %% "pprint"               % "0.9.4"
libraryDependencies += "io.github.nafg.scalac-options" %% "scalac-options"       % "0.3.0"
libraryDependencies += "io.circe"                      %% "circe-generic-extras" % "0.14.4"
libraryDependencies += "io.circe"                      %% "circe-yaml-v12"       % "1.15.0"
