libraryDependencies += "com.lihaoyi"                   %% "os-lib"               % "0.9.3"
libraryDependencies += "com.lihaoyi"                   %% "ujson"                % "3.2.0"
libraryDependencies += "com.lihaoyi"                   %% "pprint"               % "0.8.1"
libraryDependencies += "io.github.nafg.scalac-options" %% "scalac-options"       % "0.2.0"
libraryDependencies += "io.circe"                      %% "circe-generic-extras" % "0.14.3"
libraryDependencies += "io.circe"                      %% "circe-yaml-v12"       % "1.15.0"
