addSbtPlugin("org.scala-js"           % "sbt-scalajs"                % "1.16.0")
addSbtPlugin("ch.epfl.scala"          % s"sbt-scalajs-bundler"       % "0.21.1")
addSbtPlugin("com.github.sbt"         % "sbt-dynver"                 % "5.0.1")
addSbtPlugin("com.github.sbt"         % "sbt-ci-release"             % "1.6.1")
addSbtPlugin("io.github.nafg.mergify" % "sbt-mergify-github-actions" % "0.9.0")
